os: linux

language: go

go:
  - 1.14.x

env:
  global:
    - APP_DB_USERNAME=postgres
    - APP_DB_PASSWORD=
    - APP_DB_NAME=postgres

services:
  - postgresql
  - docker

script:
  # Test the code 
  - go test -v ./...
  - echo "$REGISTRY_PASSWORS" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t s1810/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag s1810/demo:latest s1810/demo:$GIT_SHA
  - docker push s1810/demo:latest
  - docker push s1810/demo:$GIT_SHA